### ISSUE TITLE
Error while installing plugin on Odoo 12

### ISSUE THREAD

**Issue by Garcicasti** [aumengse/Odoo#1]
When I try to install this plugin on Odoo 12 CE, i get the following error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(1,).lang', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-116>", line 2, in create
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/mail/models/mail_thread.py", line 292, in create
    track_threads = threads.with_context(lang=self.env.user.lang)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1045, in _compute_value
    self.compute(records)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 612, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/models.py", line 5126, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1003, in __set__
    value = self.convert_to_cache(value, record)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1966, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.users.lang: 'es_AR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-116>", line 2, in create
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/mail/models/mail_thread.py", line 292, in create
    track_threads = threads.with_context(lang=self.env.user.lang)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1045, in _compute_value
    self.compute(records)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 612, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/models.py", line 5126, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1003, in __set__
    value = self.convert_to_cache(value, record)
  File "/opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/fields.py", line 1966, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
odoo.tools.convert.ParseError: "Wrong value for res.users.lang: 'es_AR'" while parsing /opt/odoo-12.0.20190718-0/apps/odoo/lib/odoo-12.0.post20190718-py3.7.egg/odoo/addons/automatic_backup/data/data.xml:5, near
<record id="automatic_backup_record" model="automatic.backup"/>

**Comment by aumengse** [comment]
it is upon installing?

**Comment by Garcicasti** [comment]
It happends just when I click on the "Install" button.

**Comment by Garcicasti** [comment]
Any idea?

**Comment by aumengse** [comment]
will check it on my local. will get back to you once i tested it.

**Comment by aumengse** [comment]
when i install it on mine. its okay
